services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    container_name: gameApp-database
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=GameAppRootPass
      - MYSQL_DATABASE=gameApp
      - MYSQL_USER=gameApp
      - MYSQL_PASSWORD=GameAppRootPass

volumes:
  mysql_data: {}
